#pragma once

#define _SUCCESS_ 0
#define _FAILED_ 1

#define _EXCEPTION_ERROR_ -101

#define _CONNECTION_SUCESSFULL_ -200
#define _CONNECTION_FAILED_ -201
#define _CONNECTION_ON_ -202
#define _CONNECTION_OFF_ -203
#define _CONNECTION_ALREADY_OPEN_ -204

#define _ARTICLE_ADDED_ -300
#define _ARTICLE_MODIFIED_ -301
#define _ARTICLE_NOT_ADDED_ -302
#define _ARTICLE_REMOVED_ -303
#define _ARTICLE_NOT_REMOVED_ -304
#define _ARTICLE_DESCRIPTION_SET_ -305
#define _ARTICLE_DESCRIPTION_NOT_SET_ -306
#define _ARTICLE_TARE_ADDED_ -307
#define _ARTICLE_TARE_NOT_ADDED_ -308
#define _ARTICLE_TARE_REMOVED_ -309
#define _ARTICLE_TARE_NOT_REMOVED_ -310
#define _ARTICLE_TRACEABILITY_SET_ -311
#define _ARTICLE_TRACEABILITY_NOT_SET_ -312
#define _ARTICLE_NUTINFO_SET_ -313
#define _ARTICLE_NUTINFO_NOT_SET_ -314

#define _FAMILY_ADDED_ -400
#define _FAMILY_MODIFIED_ -401
#define _FAMILY_NOT_ADDED_ -402
#define _INVALID_DEPARTMENT_ -403
#define _FAMILY_REMOVED_ -404
#define _FAMILY_NOT_REMOVED_ -405

#define _CLIENT_ADDED_ -500
#define _CLIENT_MODIFIED_ -501
#define _CLIENT_NOT_ADDED_ -502
#define _CLIENT_REMOVED_ -503
#define _CLIENT_NOT_REMOVED_ -504

#define _TRACEABILITY_ADDED_ -600
#define _TRACEABILITY_MODIFIED_ -601
#define _TRACEABILITY_NOT_ADDED_ -602
#define _TRACEABILITY_REMOVED_ -603
#define _TRACEABILITY_NOT_REMOVED_ -604

#define _NUTRITIONAL_ADDED_ -700
#define _NUTRITIONAL_MODIFIED_ -701
#define _NUTRITIONAL_NOT_ADDED_ -702
#define _NUTRITIONAL_REMOVED_ -703
#define _NUTRITIONAL_NOT_REMOVED_ -704

#define _VENDOR_ADDED_ -800
#define _VENDOR_MODIFIED_ -801
#define _VENDOR_NOT_ADDED_ -802
#define _VENDOR_REMOVED_ -803
#define _VENDOR_NOT_REMOVED_ -804

#define _DEPARTMENT_ADDED_ -900
#define _EXISTING_DEPARTMENT_ -901
#define _DEPARTMENT_NOT_ADDED_ -902
#define _DEPARTMENT_REMOVED_ -903
#define _DEPARTMENT_NOT_REMOVED_ -904
#define _DEPARTMENT_HEADER_REMOVED_ -905
#define _DEPARTMENT_HEADER_NOT_REMOVED_ -906
#define _DEPARTMENT_FOOTER_REMOVED_ -907
#define _DEPARTMENT_FOOTER_NOT_REMOVED_ -908
#define _DEPARTMENT_LABEL_REMOVED_ -909
#define _DEPARTMENT_LABEL_NOT_REMOVED_ -910
#define _DEPARTMENT_HEADER_ALL_REMOVED_ -911
#define _DEPARTMENT_FOOTER_ALL_REMOVED_ -912
#define _DEPARTMENT_LABEL_ALL_REMOVED_ -913
#define _DEPARTMENT_HEADER_ADDED_ -914
#define _DEPARTMENT_FOOTER_ADDED_ -915
#define _DEPARTMENT_LABEL_ADDED_ -916
#define _DEPARTMENT_HEADER_NOT_ADDED_ -917
#define _DEPARTMENT_FOOTER_NOT_ADDED_ -918
#define _DEPARTMENT_LABEL_NOT_ADDED_ -919

#define _TARE_ADDED_ -1000
#define _TARE_MODIFIED_ -1001
#define _TARE_NOT_ADDED_ -1002
#define _TARE_REMOVED_ -1003
#define _TARE_NOT_REMOVED_ -1004

#define _VAT_ADDED_ -1100
#define _VAT_MODIFIED_ -1101
#define _VAT_NOT_ADDED_ -1102
#define _VAT_REMOVED_ -1103
#define _VAT_NOT_REMOVED_ -1104

#define _SCALE_HEADER_ADDED_ -1200
#define _SCALE_FOOTER_ADDED_ -1201
#define _SCALE_HEADER_NOT_ADDED_ -1202
#define _SCALE_FOOTER_NOT_ADDED_ -1203
#define _SCALE_HEADER_REMOVED_ -1204
#define _SCALE_FOOTER_REMOVED_ -1205
#define _SCALE_HEADER_NOT_REMOVED_ -1206
#define _SCALE_FOOTER_NOT_REMOVED_ -1207

#define _EXISTING_KEYCODE_ 1062

#define _CRT_SECURE_NO_WARNINGS