#pragma once

#define _SUCCESS_ 0
#define _FAILED_ 1

#define _EXCEPTION_ERROR_ -11

#define _CONNECTION_SUCESSFULL_ -20
#define _CONNECTION_FAILED_ -21
#define _CONNECTION_ON_ -22
#define _CONNECTION_OFF_ -23
#define _CONNECTION_ALREADY_OPEN_ -24

#define _ARTICLE_ADDED_ -30
#define _ARTICLE_MODIFIED_ -31
#define _ARTICLE_NOT_ADDED_ -32
#define _ARTICLE_REMOVED_ -33
#define _ARTICLE_NOT_REMOVED_ -34
#define _ARTICLE_DESCRIPTION_SET_ -35
#define _ARTICLE_DESCRIPTION_NOT_SET_ -36

#define _FAMILY_ADDED_ -40
#define _FAMILY_MODIFIED_ -41
#define _FAMILY_NOT_ADDED_ -42
#define _INVALID_DEPARTMENT_ -43
#define _FAMILY_REMOVED_ -44
#define _FAMILY_NOT_REMOVED_ -45

#define _CLIENT_ADDED_ -50
#define _CLIENT_MODIFIED_ -51
#define _CLIENT_NOT_ADDED_ -52
#define _CLIENT_REMOVED_ -53
#define _CLIENT_NOT_REMOVED_ -54

#define _TRACEABILITY_ADDED_ -60
#define _TRACEABILITY_MODIFIED_ -61
#define _TRACEABILITY_NOT_ADDED_ -62
#define _TRACEABILITY_REMOVED_ -63
#define _TRACEABILITY_NOT_REMOVED_ -64

#define _NUTRITIONAL_ADDED_ -70
#define _NUTRITIONAL_MODIFIED_ -71
#define _NUTRITIONAL_NOT_ADDED_ -72
#define _NUTRITIONAL_REMOVED_ -73
#define _NUTRITIONAL_NOT_REMOVED_ -74

#define _EXISTING_KEYCODE_ 1062